print("digite um numero")
numero1=input()
print("digite outro numero")
numero2=input()
adição=int(numero1) + int(numero2)
print("asoma é " + str(adição))
print("digite outro numero")
numero3=input()
subitração=int(numero2) - int(numero3)
print("subitração é " + str(subitração))
print("digite outro numero")
numero4=input()
mutiplicação=int(numero3) * int(numero4)
print("mutiplicaçã é " + str(mutiplicação))
print("digite outro numero")
numero5=input()
divisão=int(numero4) / int(numero5)
print("divisão é " + str(divisão))