print("digite um numero")
numero1=input()
print("digite outro numero")
numero2=input()
adição=int(numero1) + int(numero2)
print("asoma é " + str(adição))
subitração=int(numero1) - int(numero2)
print("subitração é " + str(subitração))
mutiplicação=int(numero1) * int(numero2)
print("mutiplicaçã é " + str(mutiplicação))
divisão=int(numero1) / int(numero2)
print("divisão é " + str(divisão))