print("digite um numero")
numero1=input()
print("digite outro numero")
numero2=input()
print("digite outro numero")
numero3=input()
soma=int(numero1) + int(numero2) + int(numero3)
print("asoma é " + str(soma))